server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    keyId: LTAI5tRfQon4RwNGugQKymn6
    keySecret: rOV9FOenmQMegJsEIDgTz5VVdwH7NI
    bucketName: srb-file-1015